version: "3"
services:
  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo.yaml
    volumes:
    - ./etc/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3300:3300"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  tempo-query:
    image: grafana/tempo-query:latest
    command: ["--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
      - ./etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    volumes:
    - ./etc/otel-collector-config.yaml:/etc/otel-collector/config.yaml
    command: --config=/etc/otel-collector/config.yaml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  grafana-agent:
    image: grafana/agent:v0.9.1
    volumes:
      - ./etc/agent2.yaml:/etc/agent-config/agent.yaml
    command:  -config.file=/etc/agent-config/agent.yaml   --prometheus.wal-directory=/tmp/agent/wal
    ports:
      -  "12345:12345"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  victoriametrics:
    image: victoriametrics/victoria-metrics
    volumes:
      - ./example-data/victoriametrics:/victoriametrics
    ports:
      - "8428:8428"
    command: 
      - '-storageDataPath=/victoriametrics'
      - '-retentionPeriod=1'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    volumes:
      - ./etc/load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - JAEGER_COLLECTOR_URL=http://grafana-agent:14268
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  grafana:
    image: grafana/grafana:7.3.6
    volumes:
      - ./example-data/datasources:/etc/grafana/provisioning/datasources
      - ./example-data/dashboards-provisioning:/etc/grafana/provisioning/dashboard
    ports:
      - "3000:3000"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
  loki:
    image: grafana/loki:2.1.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"                                
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'